name: URL-shortener tests

on:
  push:
    branches: [ main, origin ]
  pull_request:
    branches: [ main, origin ]

jobs:
  test-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Run memory tests
        run: go test -v ./internal/domain/usecase/... -run WithPostgres

  test-postgres-mock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Run postgres mock tests
        run: go test -v ./internal/domain/usecase/... -run WithMemory